# Generated by Django 3.1.5 on 2022-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220331_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='osigbemes', max_length=255),
            preserve_default=False,
        ),
    ]
